#:schema node_modules/wrangler/config-schema.json
name = "cipowell"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [
    "nodejs_compat"
]
compatibility_date = "2025-09-01"
preview_urls = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

######## PREVIEW environment config ########

[env.preview.vars]
CONTENTFUL_HOST = "preview.contentful.com"


######## PRODUCTION environment config ########

[env.production.vars]
