#:schema node_modules/wrangler/config-schema.json
name = "cipowell"
compatibility_flags = [
    "nodejs_compat"
]
compatibility_date = "2025-09-01"
preview_urls = true

[assets]
directory = ".svelte-kit/cloudflare"
not_found_handling = "single-page-application"

######## PREVIEW environment config ########

[env.preview.vars]
CONTENTFUL_HOST = "preview.contentful.com"


######## PRODUCTION environment config ########

[env.production.vars]
